services:
  db:
    image: postgres:16
    container_name: erasmusstay_db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: erasmusstay_backend
    restart: always
    volumes:
      - ./backend/src/config:/app/config
      - ./backend/src/housing:/app/housing
      - ./backend/src/manage.py:/app/manage.py
      - ./backend/src/create_data.py:/app/create_data.py
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: erasmusstay_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: