# Generated by Django 5.2.14 on 2026-05-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='imagenanuncio',
            options={'ordering': ['orden'], 'verbose_name': 'Imagen del Anuncio', 'verbose_name_plural': 'Imágenes de Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='valoracion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Valoración', 'verbose_name_plural': 'Valoraciones'},
        ),
    ]
