# Generated by Django 5.2.14 on 2026-06-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_imagenes_solicitudes_moderacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenanuncio',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Imagen del Anuncio', 'verbose_name_plural': 'Imágenes de Anuncios'},
        ),
    ]
